[2022-12-09T18:42:09.072+0000] {processor.py:154} INFO - Started process (PID=33) to work on /opt/airflow/dags/dags.py
[2022-12-09T18:42:09.074+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T18:42:09.075+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:42:09.075+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T18:42:09.139+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:42:09.134+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T18:42:09.144+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T18:42:09.178+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.113 seconds
[2022-12-09T18:42:39.645+0000] {processor.py:154} INFO - Started process (PID=98) to work on /opt/airflow/dags/dags.py
[2022-12-09T18:42:39.649+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T18:42:39.653+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:42:39.652+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T18:42:39.693+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:42:39.686+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T18:42:39.696+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T18:42:39.750+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.111 seconds
[2022-12-09T18:43:10.104+0000] {processor.py:154} INFO - Started process (PID=153) to work on /opt/airflow/dags/dags.py
[2022-12-09T18:43:10.188+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T18:43:10.225+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:43:10.224+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T18:43:10.362+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:43:10.343+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T18:43:10.373+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T18:43:11.124+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 1.026 seconds
[2022-12-09T18:43:41.553+0000] {processor.py:154} INFO - Started process (PID=218) to work on /opt/airflow/dags/dags.py
[2022-12-09T18:43:41.558+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T18:43:41.561+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:43:41.561+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T18:43:41.619+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:43:41.611+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T18:43:41.621+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T18:43:41.647+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.106 seconds
[2022-12-09T18:44:12.293+0000] {processor.py:154} INFO - Started process (PID=283) to work on /opt/airflow/dags/dags.py
[2022-12-09T18:44:12.296+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T18:44:12.298+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:44:12.298+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T18:44:12.331+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:44:12.326+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T18:44:12.335+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T18:44:12.363+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.074 seconds
[2022-12-09T18:44:43.458+0000] {processor.py:154} INFO - Started process (PID=338) to work on /opt/airflow/dags/dags.py
[2022-12-09T18:44:43.682+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T18:44:43.769+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:44:43.769+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T18:44:43.947+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:44:43.919+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T18:44:43.950+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T18:44:44.165+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.733 seconds
[2022-12-09T18:45:15.600+0000] {processor.py:154} INFO - Started process (PID=401) to work on /opt/airflow/dags/dags.py
[2022-12-09T18:45:15.610+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T18:45:15.615+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:45:15.615+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T18:45:15.698+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:45:15.688+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T18:45:15.701+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T18:45:16.232+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.673 seconds
[2022-12-09T18:45:46.704+0000] {processor.py:154} INFO - Started process (PID=465) to work on /opt/airflow/dags/dags.py
[2022-12-09T18:45:46.714+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T18:45:46.720+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:45:46.720+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T18:45:46.797+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:45:46.786+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T18:45:46.800+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T18:45:46.865+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.168 seconds
[2022-12-09T18:46:17.365+0000] {processor.py:154} INFO - Started process (PID=529) to work on /opt/airflow/dags/dags.py
[2022-12-09T18:46:17.370+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T18:46:17.373+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:46:17.373+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T18:46:17.413+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:46:17.408+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T18:46:17.416+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T18:46:17.453+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.093 seconds
[2022-12-09T18:46:47.612+0000] {processor.py:154} INFO - Started process (PID=584) to work on /opt/airflow/dags/dags.py
[2022-12-09T18:46:47.616+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T18:46:47.621+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:46:47.621+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T18:46:47.668+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:46:47.661+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T18:46:47.675+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T18:46:47.721+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.115 seconds
[2022-12-09T18:47:18.569+0000] {processor.py:154} INFO - Started process (PID=648) to work on /opt/airflow/dags/dags.py
[2022-12-09T18:47:18.572+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T18:47:18.574+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:47:18.574+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T18:47:18.614+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:47:18.611+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T18:47:18.617+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T18:47:18.648+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.083 seconds
[2022-12-09T18:47:49.116+0000] {processor.py:154} INFO - Started process (PID=712) to work on /opt/airflow/dags/dags.py
[2022-12-09T18:47:49.123+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T18:47:49.126+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:47:49.126+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T18:47:49.183+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:47:49.170+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T18:47:49.185+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T18:47:49.260+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.150 seconds
[2022-12-09T18:48:19.964+0000] {processor.py:154} INFO - Started process (PID=776) to work on /opt/airflow/dags/dags.py
[2022-12-09T18:48:19.967+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T18:48:19.972+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:48:19.971+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T18:48:20.016+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:48:20.010+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T18:48:20.022+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T18:48:20.072+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.121 seconds
[2022-12-09T18:48:50.728+0000] {processor.py:154} INFO - Started process (PID=832) to work on /opt/airflow/dags/dags.py
[2022-12-09T18:48:50.734+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T18:48:50.738+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:48:50.737+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T18:48:50.799+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:48:50.794+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T18:48:50.801+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T18:48:50.859+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.137 seconds
[2022-12-09T18:49:20.938+0000] {processor.py:154} INFO - Started process (PID=896) to work on /opt/airflow/dags/dags.py
[2022-12-09T18:49:20.940+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T18:49:20.943+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:49:20.942+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T18:49:20.978+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:49:20.973+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T18:49:20.980+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T18:49:21.015+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.083 seconds
[2022-12-09T18:49:51.863+0000] {processor.py:154} INFO - Started process (PID=959) to work on /opt/airflow/dags/dags.py
[2022-12-09T18:49:51.870+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T18:49:51.872+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:49:51.872+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T18:49:51.909+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:49:51.905+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T18:49:51.913+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T18:49:51.961+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.104 seconds
[2022-12-09T18:50:22.177+0000] {processor.py:154} INFO - Started process (PID=1014) to work on /opt/airflow/dags/dags.py
[2022-12-09T18:50:22.181+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T18:50:22.183+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:50:22.183+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T18:50:22.220+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:50:22.216+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T18:50:22.221+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T18:50:22.260+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.088 seconds
[2022-12-09T18:50:52.972+0000] {processor.py:154} INFO - Started process (PID=1078) to work on /opt/airflow/dags/dags.py
[2022-12-09T18:50:52.973+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T18:50:52.975+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:50:52.974+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T18:50:52.992+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:50:52.990+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T18:50:52.993+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T18:50:53.014+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.046 seconds
[2022-12-09T18:51:23.561+0000] {processor.py:154} INFO - Started process (PID=1142) to work on /opt/airflow/dags/dags.py
[2022-12-09T18:51:23.565+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T18:51:23.568+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:51:23.568+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T18:51:23.618+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:51:23.611+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T18:51:23.625+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T18:51:23.678+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.138 seconds
[2022-12-09T18:51:53.890+0000] {processor.py:154} INFO - Started process (PID=1206) to work on /opt/airflow/dags/dags.py
[2022-12-09T18:51:53.893+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T18:51:53.895+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:51:53.894+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T18:51:53.938+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:51:53.934+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T18:51:53.939+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T18:51:53.960+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.077 seconds
[2022-12-09T18:52:24.284+0000] {processor.py:154} INFO - Started process (PID=1270) to work on /opt/airflow/dags/dags.py
[2022-12-09T18:52:24.287+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T18:52:24.290+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:52:24.290+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T18:52:24.309+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:52:24.307+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T18:52:24.310+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T18:52:24.326+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.050 seconds
[2022-12-09T18:52:55.024+0000] {processor.py:154} INFO - Started process (PID=1335) to work on /opt/airflow/dags/dags.py
[2022-12-09T18:52:55.031+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T18:52:55.037+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:52:55.037+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T18:52:55.083+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:52:55.077+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T18:52:55.091+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T18:52:55.150+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.136 seconds
[2022-12-09T18:53:25.774+0000] {processor.py:154} INFO - Started process (PID=1390) to work on /opt/airflow/dags/dags.py
[2022-12-09T18:53:25.778+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T18:53:25.781+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:53:25.781+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T18:53:25.842+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:53:25.832+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T18:53:25.847+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T18:53:25.928+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.173 seconds
[2022-12-09T18:53:56.040+0000] {processor.py:154} INFO - Started process (PID=1456) to work on /opt/airflow/dags/dags.py
[2022-12-09T18:53:56.043+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T18:53:56.045+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:53:56.044+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T18:53:56.083+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:53:56.079+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T18:53:56.088+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T18:53:56.117+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.088 seconds
[2022-12-09T18:54:27.043+0000] {processor.py:154} INFO - Started process (PID=1522) to work on /opt/airflow/dags/dags.py
[2022-12-09T18:54:27.050+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T18:54:27.055+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:54:27.055+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T18:54:27.123+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:54:27.107+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T18:54:27.130+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T18:54:27.162+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.130 seconds
[2022-12-09T18:54:57.926+0000] {processor.py:154} INFO - Started process (PID=1586) to work on /opt/airflow/dags/dags.py
[2022-12-09T18:54:57.928+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T18:54:57.931+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:54:57.930+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T18:54:57.987+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:54:57.974+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T18:54:57.998+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T18:54:58.045+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.127 seconds
[2022-12-09T18:55:28.855+0000] {processor.py:154} INFO - Started process (PID=1640) to work on /opt/airflow/dags/dags.py
[2022-12-09T18:55:28.862+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T18:55:28.865+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:55:28.865+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T18:55:28.903+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:55:28.897+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T18:55:28.904+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T18:55:28.971+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.122 seconds
[2022-12-09T18:55:59.897+0000] {processor.py:154} INFO - Started process (PID=1704) to work on /opt/airflow/dags/dags.py
[2022-12-09T18:55:59.900+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T18:55:59.902+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:55:59.902+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T18:55:59.933+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:55:59.928+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T18:55:59.934+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T18:55:59.968+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.077 seconds
[2022-12-09T18:56:30.236+0000] {processor.py:154} INFO - Started process (PID=1768) to work on /opt/airflow/dags/dags.py
[2022-12-09T18:56:30.238+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T18:56:30.240+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:56:30.240+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T18:56:30.261+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:56:30.258+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T18:56:30.266+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T18:56:30.282+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.050 seconds
[2022-12-09T18:57:00.977+0000] {processor.py:154} INFO - Started process (PID=1823) to work on /opt/airflow/dags/dags.py
[2022-12-09T18:57:00.979+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T18:57:00.981+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:57:00.981+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T18:57:01.026+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:57:01.018+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T18:57:01.027+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T18:57:01.069+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.097 seconds
[2022-12-09T18:57:31.158+0000] {processor.py:154} INFO - Started process (PID=1887) to work on /opt/airflow/dags/dags.py
[2022-12-09T18:57:31.160+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T18:57:31.162+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:57:31.162+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T18:57:31.184+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:57:31.182+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T18:57:31.185+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T18:57:31.208+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.057 seconds
[2022-12-09T18:58:01.434+0000] {processor.py:154} INFO - Started process (PID=1950) to work on /opt/airflow/dags/dags.py
[2022-12-09T18:58:01.439+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T18:58:01.441+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:58:01.441+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T18:58:01.470+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:58:01.466+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T18:58:01.478+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T18:58:01.533+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.102 seconds
[2022-12-09T18:58:32.585+0000] {processor.py:154} INFO - Started process (PID=2015) to work on /opt/airflow/dags/dags.py
[2022-12-09T18:58:32.587+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T18:58:32.589+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:58:32.589+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T18:58:32.611+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:58:32.606+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T18:58:32.613+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T18:58:32.632+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.055 seconds
[2022-12-09T18:59:02.700+0000] {processor.py:154} INFO - Started process (PID=2071) to work on /opt/airflow/dags/dags.py
[2022-12-09T18:59:02.703+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T18:59:02.704+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:59:02.704+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T18:59:02.736+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:59:02.732+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T18:59:02.737+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T18:59:02.772+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.076 seconds
[2022-12-09T18:59:33.811+0000] {processor.py:154} INFO - Started process (PID=2135) to work on /opt/airflow/dags/dags.py
[2022-12-09T18:59:33.814+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T18:59:33.818+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:59:33.817+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T18:59:33.855+0000] {logging_mixin.py:137} INFO - [2022-12-09T18:59:33.848+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T18:59:33.857+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T18:59:33.896+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.093 seconds
[2022-12-09T19:00:04.482+0000] {processor.py:154} INFO - Started process (PID=2199) to work on /opt/airflow/dags/dags.py
[2022-12-09T19:00:04.485+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T19:00:04.490+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:00:04.490+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T19:00:04.518+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:00:04.514+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T19:00:04.520+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T19:00:04.550+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.072 seconds
[2022-12-09T19:00:35.416+0000] {processor.py:154} INFO - Started process (PID=2262) to work on /opt/airflow/dags/dags.py
[2022-12-09T19:00:35.419+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T19:00:35.420+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:00:35.420+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T19:00:35.440+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:00:35.437+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T19:00:35.441+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T19:00:35.468+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.056 seconds
[2022-12-09T19:01:06.565+0000] {processor.py:154} INFO - Started process (PID=2317) to work on /opt/airflow/dags/dags.py
[2022-12-09T19:01:06.570+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T19:01:06.573+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:01:06.572+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T19:01:06.631+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:01:06.622+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T19:01:06.637+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T19:01:06.718+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.162 seconds
[2022-12-09T19:01:36.883+0000] {processor.py:154} INFO - Started process (PID=2382) to work on /opt/airflow/dags/dags.py
[2022-12-09T19:01:36.886+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T19:01:36.891+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:01:36.890+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T19:01:36.922+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:01:36.918+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T19:01:36.924+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T19:01:36.959+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.083 seconds
[2022-12-09T19:02:07.934+0000] {processor.py:154} INFO - Started process (PID=2446) to work on /opt/airflow/dags/dags.py
[2022-12-09T19:02:07.940+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T19:02:07.944+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:02:07.943+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T19:02:07.972+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:02:07.967+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T19:02:07.974+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T19:02:08.001+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.076 seconds
[2022-12-09T19:02:38.427+0000] {processor.py:154} INFO - Started process (PID=2510) to work on /opt/airflow/dags/dags.py
[2022-12-09T19:02:38.431+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T19:02:38.433+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:02:38.433+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T19:02:38.467+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:02:38.463+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T19:02:38.471+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T19:02:38.508+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.096 seconds
[2022-12-09T19:03:09.179+0000] {processor.py:154} INFO - Started process (PID=2565) to work on /opt/airflow/dags/dags.py
[2022-12-09T19:03:09.192+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T19:03:09.194+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:03:09.194+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T19:03:09.312+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:03:09.254+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T19:03:09.319+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T19:03:09.440+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.278 seconds
[2022-12-09T19:03:39.781+0000] {processor.py:154} INFO - Started process (PID=2620) to work on /opt/airflow/dags/dags.py
[2022-12-09T19:03:39.790+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T19:03:39.799+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:03:39.799+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T19:03:39.831+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:03:39.825+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T19:03:39.834+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T19:03:39.897+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.121 seconds
[2022-12-09T19:04:10.138+0000] {processor.py:154} INFO - Started process (PID=2683) to work on /opt/airflow/dags/dags.py
[2022-12-09T19:04:10.140+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T19:04:10.141+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:04:10.141+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T19:04:10.172+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:04:10.167+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T19:04:10.174+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T19:04:10.205+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.076 seconds
[2022-12-09T19:04:40.519+0000] {processor.py:154} INFO - Started process (PID=2746) to work on /opt/airflow/dags/dags.py
[2022-12-09T19:04:40.522+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T19:04:40.524+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:04:40.524+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T19:04:40.551+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:04:40.546+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T19:04:40.553+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T19:04:40.575+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.061 seconds
[2022-12-09T19:05:10.937+0000] {processor.py:154} INFO - Started process (PID=2804) to work on /opt/airflow/dags/dags.py
[2022-12-09T19:05:10.945+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T19:05:10.947+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:05:10.947+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T19:05:10.987+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:05:10.978+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T19:05:10.991+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T19:05:11.037+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.105 seconds
[2022-12-09T19:05:41.819+0000] {processor.py:154} INFO - Started process (PID=2868) to work on /opt/airflow/dags/dags.py
[2022-12-09T19:05:41.825+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T19:05:41.829+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:05:41.828+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T19:05:41.881+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:05:41.876+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T19:05:41.890+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T19:05:42.000+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.186 seconds
[2022-12-09T19:06:12.141+0000] {processor.py:154} INFO - Started process (PID=2932) to work on /opt/airflow/dags/dags.py
[2022-12-09T19:06:12.144+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T19:06:12.145+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:06:12.145+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T19:06:12.161+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:06:12.157+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T19:06:12.162+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T19:06:12.180+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.041 seconds
[2022-12-09T19:06:42.551+0000] {processor.py:154} INFO - Started process (PID=2996) to work on /opt/airflow/dags/dags.py
[2022-12-09T19:06:42.554+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T19:06:42.557+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:06:42.556+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T19:06:42.574+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:06:42.571+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T19:06:42.575+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T19:06:42.592+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.046 seconds
[2022-12-09T19:07:13.487+0000] {processor.py:154} INFO - Started process (PID=3051) to work on /opt/airflow/dags/dags.py
[2022-12-09T19:07:13.490+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T19:07:13.492+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:07:13.491+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T19:07:13.509+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:07:13.507+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T19:07:13.511+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T19:07:13.532+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.049 seconds
[2022-12-09T19:07:43.566+0000] {processor.py:154} INFO - Started process (PID=3115) to work on /opt/airflow/dags/dags.py
[2022-12-09T19:07:43.567+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T19:07:43.569+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:07:43.569+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T19:07:43.581+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:07:43.579+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T19:07:43.582+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T19:07:43.595+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.031 seconds
[2022-12-09T19:08:13.980+0000] {processor.py:154} INFO - Started process (PID=3180) to work on /opt/airflow/dags/dags.py
[2022-12-09T19:08:13.982+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T19:08:13.983+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:08:13.983+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T19:08:13.995+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:08:13.993+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T19:08:13.997+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T19:08:14.012+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.035 seconds
[2022-12-09T19:08:44.480+0000] {processor.py:154} INFO - Started process (PID=3244) to work on /opt/airflow/dags/dags.py
[2022-12-09T19:08:44.482+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T19:08:44.486+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:08:44.486+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T19:08:44.518+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:08:44.514+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T19:08:44.526+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T19:08:44.572+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.102 seconds
[2022-12-09T19:09:15.527+0000] {processor.py:154} INFO - Started process (PID=3308) to work on /opt/airflow/dags/dags.py
[2022-12-09T19:09:15.528+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T19:09:15.529+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:09:15.529+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T19:09:15.545+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:09:15.543+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T19:09:15.546+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T19:09:15.565+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.042 seconds
[2022-12-09T19:09:46.118+0000] {processor.py:154} INFO - Started process (PID=3363) to work on /opt/airflow/dags/dags.py
[2022-12-09T19:09:46.120+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T19:09:46.122+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:09:46.122+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T19:09:46.154+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:09:46.151+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T19:09:46.155+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T19:09:46.178+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.075 seconds
[2022-12-09T19:10:16.729+0000] {processor.py:154} INFO - Started process (PID=3427) to work on /opt/airflow/dags/dags.py
[2022-12-09T19:10:16.730+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T19:10:16.733+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:10:16.733+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T19:10:16.753+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:10:16.750+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T19:10:16.755+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T19:10:16.769+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.046 seconds
[2022-12-09T19:10:47.233+0000] {processor.py:154} INFO - Started process (PID=3491) to work on /opt/airflow/dags/dags.py
[2022-12-09T19:10:47.236+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T19:10:47.237+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:10:47.237+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T19:10:47.256+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:10:47.254+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T19:10:47.258+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T19:10:47.277+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.048 seconds
[2022-12-09T19:11:17.339+0000] {processor.py:154} INFO - Started process (PID=3555) to work on /opt/airflow/dags/dags.py
[2022-12-09T19:11:17.345+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T19:11:17.348+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:11:17.348+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T19:11:17.373+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:11:17.370+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T19:11:17.374+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T19:11:17.397+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.060 seconds
[2022-12-09T19:11:47.610+0000] {processor.py:154} INFO - Started process (PID=3613) to work on /opt/airflow/dags/dags.py
[2022-12-09T19:11:47.618+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T19:11:47.620+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:11:47.620+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T19:11:47.656+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:11:47.652+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T19:11:47.658+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T19:11:47.713+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.115 seconds
[2022-12-09T19:12:18.359+0000] {processor.py:154} INFO - Started process (PID=3670) to work on /opt/airflow/dags/dags.py
[2022-12-09T19:12:18.369+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T19:12:18.379+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:12:18.379+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T19:12:18.549+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:12:18.526+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T19:12:18.558+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T19:12:18.741+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.427 seconds
[2022-12-09T19:12:49.093+0000] {processor.py:154} INFO - Started process (PID=3733) to work on /opt/airflow/dags/dags.py
[2022-12-09T19:12:49.096+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T19:12:49.098+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:12:49.098+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T19:12:49.127+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:12:49.123+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T19:12:49.128+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T19:12:49.159+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.074 seconds
[2022-12-09T19:13:19.212+0000] {processor.py:154} INFO - Started process (PID=3797) to work on /opt/airflow/dags/dags.py
[2022-12-09T19:13:19.215+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T19:13:19.217+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:13:19.216+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T19:13:19.234+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:13:19.232+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T19:13:19.236+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T19:13:19.258+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.050 seconds
[2022-12-09T19:13:50.008+0000] {processor.py:154} INFO - Started process (PID=3861) to work on /opt/airflow/dags/dags.py
[2022-12-09T19:13:50.010+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T19:13:50.013+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:13:50.013+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T19:13:50.038+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:13:50.034+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T19:13:50.044+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T19:13:50.404+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.400 seconds
[2022-12-09T19:14:21.316+0000] {processor.py:154} INFO - Started process (PID=3915) to work on /opt/airflow/dags/dags.py
[2022-12-09T19:14:21.331+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T19:14:21.334+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:14:21.334+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T19:14:21.370+0000] {logging_mixin.py:137} INFO - [2022-12-09T19:14:21.355+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T19:14:21.372+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T19:14:21.401+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.092 seconds
[2022-12-09T20:18:28.944+0000] {processor.py:154} INFO - Started process (PID=3938) to work on /opt/airflow/dags/dags.py
[2022-12-09T20:18:28.973+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T20:18:28.984+0000] {logging_mixin.py:137} INFO - [2022-12-09T20:18:28.984+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T20:18:29.124+0000] {logging_mixin.py:137} INFO - [2022-12-09T20:18:29.117+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T20:18:29.139+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T20:18:29.247+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.328 seconds
[2022-12-09T21:09:07.135+0000] {processor.py:154} INFO - Started process (PID=4000) to work on /opt/airflow/dags/dags.py
[2022-12-09T21:09:07.144+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T21:09:07.150+0000] {logging_mixin.py:137} INFO - [2022-12-09T21:09:07.150+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T21:09:07.276+0000] {logging_mixin.py:137} INFO - [2022-12-09T21:09:07.245+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T21:09:07.284+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T21:09:07.368+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.251 seconds
[2022-12-09T22:16:03.509+0000] {processor.py:154} INFO - Started process (PID=4055) to work on /opt/airflow/dags/dags.py
[2022-12-09T22:16:03.517+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T22:16:03.524+0000] {logging_mixin.py:137} INFO - [2022-12-09T22:16:03.524+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T22:16:03.589+0000] {logging_mixin.py:137} INFO - [2022-12-09T22:16:03.581+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T22:16:03.593+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T22:16:03.904+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 0.402 seconds
[2022-12-09T23:21:35.663+0000] {processor.py:154} INFO - Started process (PID=4119) to work on /opt/airflow/dags/dags.py
[2022-12-09T23:21:35.824+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-12-09T23:21:35.835+0000] {logging_mixin.py:137} INFO - [2022-12-09T23:21:35.835+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-12-09T23:21:36.159+0000] {logging_mixin.py:137} INFO - [2022-12-09T23:21:36.141+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 54, in <module>
    [task_1,task_2] >> task_3 >> [task_5,task_6,task_7] >> [task_8,task_9]
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2022-12-09T23:21:36.164+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-12-09T23:21:36.371+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dags.py took 1.658 seconds
