[2022-12-17T10:00:32.678+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Can_I_change_name_to_this.task_12 scheduled__2022-12-16T10:00:00+00:00 [queued]>
[2022-12-17T10:00:32.805+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Can_I_change_name_to_this.task_12 scheduled__2022-12-16T10:00:00+00:00 [queued]>
[2022-12-17T10:00:32.813+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-17T10:00:32.816+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-17T10:00:32.819+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-17T10:00:32.993+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): task_12> on 2022-12-16 10:00:00+00:00
[2022-12-17T10:00:33.066+0000] {standard_task_runner.py:55} INFO - Started process 2142 to run task
[2022-12-17T10:00:33.244+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Can_I_change_name_to_this', 'task_12', 'scheduled__2022-12-16T10:00:00+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmpd56ua24q']
[2022-12-17T10:00:33.302+0000] {standard_task_runner.py:83} INFO - Job 121: Subtask task_12
[2022-12-17T10:00:34.630+0000] {task_command.py:389} INFO - Running <TaskInstance: Can_I_change_name_to_this.task_12 scheduled__2022-12-16T10:00:00+00:00 [running]> on host 502390ac5559
[2022-12-17T10:00:36.269+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Can_I_change_name_to_this
AIRFLOW_CTX_TASK_ID=task_12
AIRFLOW_CTX_EXECUTION_DATE=2022-12-16T10:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-16T10:00:00+00:00
[2022-12-17T10:00:36.400+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-12-17T10:00:36.502+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/tasks/redshift/basic_load_to_redshift.py']
[2022-12-17T10:00:37.199+0000] {subprocess.py:86} INFO - Output:
[2022-12-17T10:00:44.503+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2022-12-17T10:00:44.659+0000] {subprocess.py:93} INFO -   File "/opt/***/tasks/redshift/basic_load_to_redshift.py", line 10, in <module>
[2022-12-17T10:00:44.665+0000] {subprocess.py:93} INFO -     from logger.Logger import Log
[2022-12-17T10:00:44.669+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'logger'
[2022-12-17T10:00:44.733+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2022-12-17T10:00:48.020+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-12-17T10:00:48.373+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=Can_I_change_name_to_this, task_id=task_12, execution_date=20221216T100000, start_date=20221217T100032, end_date=20221217T100048
[2022-12-17T10:00:49.050+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 121 for task task_12 (Bash command failed. The command returned a non-zero exit code 1.; 2142)
[2022-12-17T10:00:49.501+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-17T10:00:51.544+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
